
 - name: plat 01 
   hosts: web    # which hosts your ansible server wants to connect
   tasks: # list of tasks/module/collections
   - name: play 01 task 01
     ansible.builtin.debug:
       msg: "this is from play 01 and task 01"

 - name: play 02 
   hosts: web    # which hosts your ansible server wants to connect
   tasks: # list of tasks/module/collections
   - name: play 02 task 02
     ansible.builtin.debug:
      msg: "this is from play 02 and task 02"
      
