- name: demo of functions/filters
  hosts: frontend
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"


  - name: convert to uppercase
    vars:
      greeting: "HELLO PRASHANTH"
    ansinble.builtin.debug:
      msg: " {{ greeting | upper }}"  
  