- name: demo functions
  hosts: frontend
  connection: local
  tasks: 
  - name:  task 01 and task 02
    ansible.builtin.debug:
      
  - name: convert to uppercase
    vars:
      greeting: "HELLO prashanth"
    ansinble.builtin.debug:
      msg: " {{ greeting | upper }}"


  - name: convert to lowercase
    vars:
      greeting: "HELLO prashanth"
    ansinble.builtin.debug:
      msg: " {{ greeting | lower }}"
